# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c7f23590ee310b851654146990f41571d5c5db8f73f204c15a47999465e536a5787252e8aaa10f8886adb55424a520101fda9d2ecaae36eb62961ff6798de4

test:
  secret_key_base: 6b1376bf5f8a6a36d2d1317e01affc689484feaa30721fa24ce0ce63949e2a524b95707c5b0f48cb9748816237073645340502cd2ad16b394477541e1dbe1b28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
